### PR TITLE
Profile Screen

### PR DESCRIPTION
**Pull request by sudhansubhushanmishra**
Current state
image

Still to be ok

### CODE REVIEW

**Review by iamabhishek229313 — APPROVED** [review]
It's terrific.

**Comment by sudhansubhushanmishra** [comment]
There's still an issue with this, as your fab takes a FirebaseUser and scrolling stuff might not work properly yet

**Comment by sudhansubhushanmishra** [comment]
Should this be merged yet?

**Comment by iamabhishek229313** [comment]
> There's still an issue with this, as your fab takes a FirebaseUser and scrolling stuff might not work properly yet

Put that in issue.

**Pull request merged**
